services:
- name: p-sqlserver
  id: 3101b971-1044-4816-a7ac-9ded2e028079
  description: SQLServer 2012 service for application development and testing
  tags:
    - sqlserver
    - relational
  max_db_per_node: 250
  metadata:
    provider:
      name:
    listing:
      imageUrl: ~
      blurb: SQLServer service for application development and testing
  plans:
  - name: 50mb
    id: 2451fa22-df16-4c10-ba6e-1f682d3dcdc9
    description: Shared SQLServer, 50mb persistent disk, 40 max concurrent connections
    max_storage_mb: 50 # in MB
    metadata:
      cost: 0.0
      bullets:
      - content: Shared SQLServer server
      - content: 50 MB storage
      - content: 40 concurrent connections